# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaperProtoServerStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LaunchGameRoom = channel.unary_unary(
                '/paperproto_server.PaperProtoServer/LaunchGameRoom',
                request_serializer=service__pb2.LaunchGameRoomRequest.SerializeToString,
                response_deserializer=service__pb2.LaunchGameRoomResponse.FromString,
                _registered_method=True)
        self.JoinGameRoom = channel.unary_unary(
                '/paperproto_server.PaperProtoServer/JoinGameRoom',
                request_serializer=service__pb2.JoinGameRoomRequest.SerializeToString,
                response_deserializer=service__pb2.JoinGameRoomResponse.FromString,
                _registered_method=True)
        self.GetPlayers = channel.unary_stream(
                '/paperproto_server.PaperProtoServer/GetPlayers',
                request_serializer=service__pb2.GetPlayersRequest.SerializeToString,
                response_deserializer=service__pb2.GetPlayersResponse.FromString,
                _registered_method=True)
        self.SubscribeToGameUpdates = channel.unary_stream(
                '/paperproto_server.PaperProtoServer/SubscribeToGameUpdates',
                request_serializer=service__pb2.SubscribeToGameUpdatesRequest.SerializeToString,
                response_deserializer=service__pb2.SubscribeToGameUpdatesResponse.FromString,
                _registered_method=True)
        self.SendGameUpdate = channel.unary_unary(
                '/paperproto_server.PaperProtoServer/SendGameUpdate',
                request_serializer=service__pb2.SendGameUpdateRequest.SerializeToString,
                response_deserializer=service__pb2.SendGameUpdateResponse.FromString,
                _registered_method=True)
        self.GameEnd = channel.unary_unary(
                '/paperproto_server.PaperProtoServer/GameEnd',
                request_serializer=service__pb2.GameEndRequest.SerializeToString,
                response_deserializer=service__pb2.GameEndResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/paperproto_server.PaperProtoServer/Heartbeat',
                request_serializer=service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class PaperProtoServerServicer(object):
    """The service definition.
    """

    def LaunchGameRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGameRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToGameUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGameUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GameEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaperProtoServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LaunchGameRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.LaunchGameRoom,
                    request_deserializer=service__pb2.LaunchGameRoomRequest.FromString,
                    response_serializer=service__pb2.LaunchGameRoomResponse.SerializeToString,
            ),
            'JoinGameRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGameRoom,
                    request_deserializer=service__pb2.JoinGameRoomRequest.FromString,
                    response_serializer=service__pb2.JoinGameRoomResponse.SerializeToString,
            ),
            'GetPlayers': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPlayers,
                    request_deserializer=service__pb2.GetPlayersRequest.FromString,
                    response_serializer=service__pb2.GetPlayersResponse.SerializeToString,
            ),
            'SubscribeToGameUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToGameUpdates,
                    request_deserializer=service__pb2.SubscribeToGameUpdatesRequest.FromString,
                    response_serializer=service__pb2.SubscribeToGameUpdatesResponse.SerializeToString,
            ),
            'SendGameUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGameUpdate,
                    request_deserializer=service__pb2.SendGameUpdateRequest.FromString,
                    response_serializer=service__pb2.SendGameUpdateResponse.SerializeToString,
            ),
            'GameEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.GameEnd,
                    request_deserializer=service__pb2.GameEndRequest.FromString,
                    response_serializer=service__pb2.GameEndResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=service__pb2.HeartbeatRequest.FromString,
                    response_serializer=service__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paperproto_server.PaperProtoServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paperproto_server.PaperProtoServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaperProtoServer(object):
    """The service definition.
    """

    @staticmethod
    def LaunchGameRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paperproto_server.PaperProtoServer/LaunchGameRoom',
            service__pb2.LaunchGameRoomRequest.SerializeToString,
            service__pb2.LaunchGameRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinGameRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paperproto_server.PaperProtoServer/JoinGameRoom',
            service__pb2.JoinGameRoomRequest.SerializeToString,
            service__pb2.JoinGameRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/paperproto_server.PaperProtoServer/GetPlayers',
            service__pb2.GetPlayersRequest.SerializeToString,
            service__pb2.GetPlayersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToGameUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/paperproto_server.PaperProtoServer/SubscribeToGameUpdates',
            service__pb2.SubscribeToGameUpdatesRequest.SerializeToString,
            service__pb2.SubscribeToGameUpdatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGameUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paperproto_server.PaperProtoServer/SendGameUpdate',
            service__pb2.SendGameUpdateRequest.SerializeToString,
            service__pb2.SendGameUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GameEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paperproto_server.PaperProtoServer/GameEnd',
            service__pb2.GameEndRequest.SerializeToString,
            service__pb2.GameEndResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paperproto_server.PaperProtoServer/Heartbeat',
            service__pb2.HeartbeatRequest.SerializeToString,
            service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
