/**
 * @fileoverview gRPC-Web generated client stub for paperproto_server
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.1
// source: proto/service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.paperproto_server = require('./service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.paperproto_server.PaperProtoServerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.paperproto_server.PaperProtoServerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.paperproto_server.LaunchGameRoomRequest,
 *   !proto.paperproto_server.LaunchGameRoomResponse>}
 */
const methodDescriptor_PaperProtoServer_LaunchGameRoom = new grpc.web.MethodDescriptor(
  '/paperproto_server.PaperProtoServer/LaunchGameRoom',
  grpc.web.MethodType.UNARY,
  proto.paperproto_server.LaunchGameRoomRequest,
  proto.paperproto_server.LaunchGameRoomResponse,
  /**
   * @param {!proto.paperproto_server.LaunchGameRoomRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.paperproto_server.LaunchGameRoomResponse.deserializeBinary
);


/**
 * @param {!proto.paperproto_server.LaunchGameRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.paperproto_server.LaunchGameRoomResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.LaunchGameRoomResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerClient.prototype.launchGameRoom =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/LaunchGameRoom',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_LaunchGameRoom,
      callback);
};


/**
 * @param {!proto.paperproto_server.LaunchGameRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.paperproto_server.LaunchGameRoomResponse>}
 *     Promise that resolves to the response
 */
proto.paperproto_server.PaperProtoServerPromiseClient.prototype.launchGameRoom =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/LaunchGameRoom',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_LaunchGameRoom);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.paperproto_server.JoinGameRoomRequest,
 *   !proto.paperproto_server.JoinGameRoomResponse>}
 */
const methodDescriptor_PaperProtoServer_JoinGameRoom = new grpc.web.MethodDescriptor(
  '/paperproto_server.PaperProtoServer/JoinGameRoom',
  grpc.web.MethodType.UNARY,
  proto.paperproto_server.JoinGameRoomRequest,
  proto.paperproto_server.JoinGameRoomResponse,
  /**
   * @param {!proto.paperproto_server.JoinGameRoomRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.paperproto_server.JoinGameRoomResponse.deserializeBinary
);


/**
 * @param {!proto.paperproto_server.JoinGameRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.paperproto_server.JoinGameRoomResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.JoinGameRoomResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerClient.prototype.joinGameRoom =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/JoinGameRoom',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_JoinGameRoom,
      callback);
};


/**
 * @param {!proto.paperproto_server.JoinGameRoomRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.paperproto_server.JoinGameRoomResponse>}
 *     Promise that resolves to the response
 */
proto.paperproto_server.PaperProtoServerPromiseClient.prototype.joinGameRoom =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/JoinGameRoom',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_JoinGameRoom);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.paperproto_server.GetPlayersRequest,
 *   !proto.paperproto_server.GetPlayersResponse>}
 */
const methodDescriptor_PaperProtoServer_GetPlayers = new grpc.web.MethodDescriptor(
  '/paperproto_server.PaperProtoServer/GetPlayers',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.paperproto_server.GetPlayersRequest,
  proto.paperproto_server.GetPlayersResponse,
  /**
   * @param {!proto.paperproto_server.GetPlayersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.paperproto_server.GetPlayersResponse.deserializeBinary
);


/**
 * @param {!proto.paperproto_server.GetPlayersRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.GetPlayersResponse>}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerClient.prototype.getPlayers =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/paperproto_server.PaperProtoServer/GetPlayers',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_GetPlayers);
};


/**
 * @param {!proto.paperproto_server.GetPlayersRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.GetPlayersResponse>}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerPromiseClient.prototype.getPlayers =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/paperproto_server.PaperProtoServer/GetPlayers',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_GetPlayers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.paperproto_server.SubscribeToGameUpdatesRequest,
 *   !proto.paperproto_server.SubscribeToGameUpdatesResponse>}
 */
const methodDescriptor_PaperProtoServer_SubscribeToGameUpdates = new grpc.web.MethodDescriptor(
  '/paperproto_server.PaperProtoServer/SubscribeToGameUpdates',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.paperproto_server.SubscribeToGameUpdatesRequest,
  proto.paperproto_server.SubscribeToGameUpdatesResponse,
  /**
   * @param {!proto.paperproto_server.SubscribeToGameUpdatesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.paperproto_server.SubscribeToGameUpdatesResponse.deserializeBinary
);


/**
 * @param {!proto.paperproto_server.SubscribeToGameUpdatesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.SubscribeToGameUpdatesResponse>}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerClient.prototype.subscribeToGameUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/paperproto_server.PaperProtoServer/SubscribeToGameUpdates',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_SubscribeToGameUpdates);
};


/**
 * @param {!proto.paperproto_server.SubscribeToGameUpdatesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.SubscribeToGameUpdatesResponse>}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerPromiseClient.prototype.subscribeToGameUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/paperproto_server.PaperProtoServer/SubscribeToGameUpdates',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_SubscribeToGameUpdates);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.paperproto_server.SendGameUpdateRequest,
 *   !proto.paperproto_server.SendGameUpdateResponse>}
 */
const methodDescriptor_PaperProtoServer_SendGameUpdate = new grpc.web.MethodDescriptor(
  '/paperproto_server.PaperProtoServer/SendGameUpdate',
  grpc.web.MethodType.UNARY,
  proto.paperproto_server.SendGameUpdateRequest,
  proto.paperproto_server.SendGameUpdateResponse,
  /**
   * @param {!proto.paperproto_server.SendGameUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.paperproto_server.SendGameUpdateResponse.deserializeBinary
);


/**
 * @param {!proto.paperproto_server.SendGameUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.paperproto_server.SendGameUpdateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.SendGameUpdateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerClient.prototype.sendGameUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/SendGameUpdate',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_SendGameUpdate,
      callback);
};


/**
 * @param {!proto.paperproto_server.SendGameUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.paperproto_server.SendGameUpdateResponse>}
 *     Promise that resolves to the response
 */
proto.paperproto_server.PaperProtoServerPromiseClient.prototype.sendGameUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/SendGameUpdate',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_SendGameUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.paperproto_server.GameEndRequest,
 *   !proto.paperproto_server.GameEndResponse>}
 */
const methodDescriptor_PaperProtoServer_GameEnd = new grpc.web.MethodDescriptor(
  '/paperproto_server.PaperProtoServer/GameEnd',
  grpc.web.MethodType.UNARY,
  proto.paperproto_server.GameEndRequest,
  proto.paperproto_server.GameEndResponse,
  /**
   * @param {!proto.paperproto_server.GameEndRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.paperproto_server.GameEndResponse.deserializeBinary
);


/**
 * @param {!proto.paperproto_server.GameEndRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.paperproto_server.GameEndResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.GameEndResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerClient.prototype.gameEnd =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/GameEnd',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_GameEnd,
      callback);
};


/**
 * @param {!proto.paperproto_server.GameEndRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.paperproto_server.GameEndResponse>}
 *     Promise that resolves to the response
 */
proto.paperproto_server.PaperProtoServerPromiseClient.prototype.gameEnd =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/GameEnd',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_GameEnd);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.paperproto_server.HeartbeatRequest,
 *   !proto.paperproto_server.HeartbeatResponse>}
 */
const methodDescriptor_PaperProtoServer_Heartbeat = new grpc.web.MethodDescriptor(
  '/paperproto_server.PaperProtoServer/Heartbeat',
  grpc.web.MethodType.UNARY,
  proto.paperproto_server.HeartbeatRequest,
  proto.paperproto_server.HeartbeatResponse,
  /**
   * @param {!proto.paperproto_server.HeartbeatRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.paperproto_server.HeartbeatResponse.deserializeBinary
);


/**
 * @param {!proto.paperproto_server.HeartbeatRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.paperproto_server.HeartbeatResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.paperproto_server.HeartbeatResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.paperproto_server.PaperProtoServerClient.prototype.heartbeat =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/Heartbeat',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_Heartbeat,
      callback);
};


/**
 * @param {!proto.paperproto_server.HeartbeatRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.paperproto_server.HeartbeatResponse>}
 *     Promise that resolves to the response
 */
proto.paperproto_server.PaperProtoServerPromiseClient.prototype.heartbeat =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/paperproto_server.PaperProtoServer/Heartbeat',
      request,
      metadata || {},
      methodDescriptor_PaperProtoServer_Heartbeat);
};


module.exports = proto.paperproto_server;

